serviceName: "account"
version: "v1"
grpc:
  host: "account"
  port: 9090
  max-call-recv-msg-size: 0
  max-call-send-msg-size: 0
enableTracing: false
tracing:
  metrics: "prometheus"
proxy:
  port: 8000
authRequiredMethods:
  - "/account.AccountService/List": true
  - "/account.AccountService/ListStream": true
  - "/account.AccountService/Delete": true
  - "/account.AccountService/Update": true
  - "/account.AccountService/Create": true
accessibleRoles:
  - "/account.AccountService/List":
    - admin
    - root
  - "/account.AccountService/ListStream":
    - admin
    - root
  - "/account.AccountService/Delete":
    - admin
    - root
  - "/account.AccountService/Update":
    - admin
    - root
database:
  host: "postgres"
  port: 5432
  user:  "root"
  password: "root"
  scheme: "users"
  maxIdleConns: 10
  maxOpenConns: 100
  connectTimeout: "1h"
  debug: true
enableTLS: false
TLSCert:
  CACert : "./cert/ca-cert.pem"
  CertPem: "./cert/server-cert.pem"
  KeyPem : "./cert/server-key.pem"
log:
  #PANNIC, FATAL, ERROR, WARN, INFO, DEBUG
  mode: "dev"
  level: "DEBUG"
  traceLevel: "ERROR"
  isLogFile: false
  pathLogFile: "./logFile.log"
clientConfig:
  user:
    version: "v3"
    serviceName: "user"
    grpc: 
      host: "v3"
      port: 9090
    enableTLS: false
    TLSCert:
      CACert : "./cert/ca-cert.pem"
redis:
  nodes:
    - "host.docker.internal:6379"
    # - "redis:6379"
  prefix: ""