version: '3'
services:
  client-service:
    image: grpc:service
    container_name: grpc-service
    build:
      context: .
      dockerfile: Dockerfile.service
    environment: 
      GRPC_PORT: 9090
    networks:
      - grpc-rest

  grpc-gateway:
    image: grpc-gateway:gw
    container_name: grpc-gw
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GRPC_HOST: "client-service:9090"
      PROXY_PORT: 8000
    ports:
        - 8000:8000
    networks:
      - grpc-rest
    depends_on:
      - client-service

  grpc-gateway-gen:
    image: grpc-gateway:gw
    container_name: grpc-gw
    build:
      context: ./pkg/api/v2/gen/grpc-gateway
      dockerfile: Dockerfile
    # environment:
    #   GRPC_HOST: "client-service:9090"
    #   PROXY_PORT: 8000
    ports:
        - 8000:80
    networks:
      - grpc-rest
    depends_on:
      - client-service

  envoy:
    image: envoy-proxy
    container_name: envoy-proxy
    build:
      context: ./pkg/api/v2/gen/grpc-web/envoy
    ports:
        - 7070:8080
        - 9901:9901
    networks:
      - grpc-rest
    depends_on:
      - client-service

networks:
    grpc-rest: