version: '3'
services:
  client-service:
    image: grpc-gateway:client
    container_name: grpc-gw-service
    build:
      context: .
      dockerfile: Dockerfile.service
    environment: 
      GRPC_PORT: 9090

  grpc-gateway:
    image: grpc-gateway:gw
    container_name: grpc-gw
    build:
      context: ./pkg/api/v2/gen/grpc-gateway
      dockerfile: Dockerfile
    # environment:
    #   GRPC_HOST: "client-service:9090"
    #   PROXY_PORT: 8000
    ports:
        - 8000:80
    depends_on:
      - client-service