version: '3'
services:

  client:
    image: grpc-web-client
    container_name: grpc-web-client
    build:
      context: ./pkg/api/v2/gen/grpc-web
    ports:
        - 8081:8081
    volumes:
        - node_modules:/app/node_modules
        - ./pkg/api/v2/gen/grpc-web/:/app/
    networks:
      - grpc-rest

volumes:
    node_modules:

networks:
    grpc-rest: