serviceName: "grpc-client"
version: "v3"
tracing:
  flags: true
  metrics: "prometheus"
clientConfig:
  version: "v3"
  serviceName: "v3"
  grpc: 
    host: "v3"
    port: 9090
  secure:
    flag: true
    TLSCert:
      CACert : "./cert/ca-cert.pem"