serviceName: "grpc-client"
version: "v3"
enableTracing: true
tracing:
  metrics: "prometheus"
clientConfig:
  version: "v3"
  serviceName: "v3"
  enableTracing: true
  grpc: 
    host: "v3"
    port: 9090
  enableTLS: true
  TLSCert:
    CACert : "./cert/ca-cert.pem"