serviceName: "grpc-gateway"
version: "v3"
grpc:
  host: "v3"
  port: 9090
  max-call-recv-msg-size: 0
  max-call-send-msg-size: 0
tracing:
  flags: true
  metrics: "prometheus"
proxy:
  port: 8000
jwt:
  secretKey: "lu"
  duration: "1200s"
  issuer: "lu"
accessibleRoles:
  - "/api_v3.UserService/List":
    - admin
    - root
  - "/api_v3.UserService/ListStream":
    - admin
    - root
  - "/api_v3.UserService/Delete":
    - admin
    - root
  - "/api_v3.UserService/Update":
    - admin
    - root
database:
  host: "postgres"
  port: 5432
  user:  "root"
  password: "root"
  scheme: "users"
  maxIdleConns: 10
  maxOpenConns: 100
  connectTimeout: "1h"
  debug: true
secure:
  flag: true
  TLSCert:
    CertPem: "./cert/server-cert.pem"
    KeyPem : "./cert/server-key.pem"
clientConfig:
  version: "v3"
  serviceName: "localhost:9090"
  grpc: 
    host: "localhost"
    port: 9090
  secure:
    flag: true
    TLSCert:
      CACert : "./cert/ca-cert.pem"